import type { Metadata } from "next";
import "./globals.css";
import { AIProvider } from "@/app/api/chat/AIContent";
import SideNavigation from "@/components/SideNavigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-gray-900 text-white">
      <body>
        <div className="grid grid-cols-[16rem_1fr] h-full gap-12">
          <SideNavigation />

          <div className="py-1 ">
            <AIProvider>{children}</AIProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
